// User account
export const USER_ACCOUNT_MAXIMUM_EMAIL_LENGTH = 128;

export const USER_ACCOUNT_MINIMUM_PASSWORD_LENGTH = 10;
export const USER_ACCOUNT_MAXIMUM_PASSWORD_LENGTH = 128;

export const USER_ACCOUNT_MINIMUM_FIRST_NAME_LENGTH = 1;
export const USER_ACCOUNT_MAXIMUM_FIRST_NAME_LENGTH = 128;
export const USER_ACCOUNT_MINIMUM_LAST_NAME_LENGTH = 1;
export const USER_ACCOUNT_MAXIMUM_LAST_NAME_LENGTH = 128;

// Notes
export const NOTE_MAXIMUM_CONTENT_LENGTH = 1024;
